services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: churn-app
    ports:
      - "8000:8000"
    environment:
      PYTHONUNBUFFERED: "1"
      PYTHONPATH: /app
      MODEL_DIR: /app/src/serving/model/bundle
      FEATURE_METADATA_PATH: /app/src/serving/model/metadata.json
    depends_on:
      - mlflow

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    container_name: churn-mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow.db:/mlflow/mlflow.db
      - ./mlartifacts:/mlflow/mlartifacts
