FROM python:3.11-slim

WORKDIR /mlflow

ENV PYTHONUNBUFFERED=1

RUN pip install --upgrade pip \
    && pip install --no-cache-dir mlflow \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

EXPOSE 5000

CMD ["mlflow", "server", "--backend-store-uri", "sqlite:///mlflow.db", "--default-artifact-root", "file:///mlflow/mlartifacts", "--host", "0.0.0.0", "--port", "5000"]
